target-version = "py39"

lint.select = [
    "ALL",
]

lint.preview = true

lint.ignore = [
    "ANN",
    "complex-structure",
    "missing-trailing-comma",
    "incorrect-blank-line-before-class",
    "multi-line-summary-second-line",
    "non-imperative-mood",
    "call-datetime-strptime-without-zone",
    "raw-string-in-exception",
    "f-string-in-exception",
    "commented-out-code",
    "future-rewritable-type-annotation",
    "boolean-type-hint-positional-argument",
    "boolean-default-value-positional-argument",
    "boolean-positional-value-in-call",
    "invalid-function-name",
    "too-many-return-statements",
    "too-many-branches",
    "too-many-arguments",
    "too-many-statements",
    "magic-value-comparison",
    "redefined-loop-name",
    "pytest-unittest-assertion",
    "pytest-fixture-param-without-value",
    "pytest-unittest-raises-assertion",
    "collection-literal-concatenation",
    "subprocess-popen-with-shell-equals-true",
    "subprocess-without-shell-equals-true",
    "start-process-with-partial-path",
    "print",
    "raise-vanilla-args",
    "raise-within-try",
    "non-pep604-annotation-union",
    "non-pep604-annotation-optional",

    # --preview
    "missing-copyright-notice",
    "docstring-missing-returns",
    "docstring-missing-yields",
    "docstring-missing-exception",
    "reimplemented-operator",
    "suspicious-subprocess-import",
]

lint.flake8-quotes.inline-quotes = "single"
format.quote-style = "single"
line-length = 79
