[project]
nav = [
    {"Home" = "index.md"},
    {"Installation" = "install.md"},
    {"Configuration" = [
        {"Basics" = "config/basic.md"},
        {"Sections" = [
	      "config/section/index.md",
              {"foomuuri" = "config/section/foomuuri.md"},
              {"zone" = "config/section/zone.md"},
              {"zone-zone" = "config/section/zonezone.md"},
              {"zone-any, any-zone, any-any" = "config/section/any.md"},
              {"macro" = "config/section/macro.md"},
              {"iplist" = "config/section/iplist.md"},
              {"snat" = "config/section/snat.md"},
              {"dnat" = "config/section/dnat.md"},
              {"template" = "config/section/template.md"},
              {"hook" = "config/section/hook.md"},
              {"zonemap" = "config/section/zonemap.md"},
              {"prerouting, postrouting, forward, input, output" = "config/section/special.md"},
              {"invalid, rpfilter, smurfs" = "config/section/invalid.md"},
              {"target, group" = "config/section/targetgroup.md"},
        ]},
        {"Rule" = [
	      "config/rule/index.md",
              {"Matchers" = "config/rule/matcher.md"},
              {"Statements" = "config/rule/statement.md"},
              {"Logging" = "config/rule/logging.md"},
              {"Rate Limit" = "config/rule/ratelimit.md"},
              {"Miscellaneous" = "config/rule/misc.md"},
        ]},
    ]},
    {"Examples" = [
        {"Host Firewall" = "example/host-firewall.md"},
        {"Router Firewall" = "example/router-firewall.md"},
        {"Advanced Filtering" = "example/advanced.md"},
        {"Multiple ISP" = "example/multiple-isp.md"},
    ]},
    {"Tools" = [
        {"Connectivity Monitor" =  "tool/monitor.md"},
    ]},
    {"FAQ" = "faq.md"},
]

site_name = "Foomuuri"
site_url = "https://foomuuri.foobar.fi/latest"
repo_url = "https://github.com/FoobarOy/foomuuri"
copyright = "Copyright 2023-2026, Kim B. Heino, Foobar Oy and contributors."

[project.extra.version]
provider = "mike"
alias = true

[project.theme]
custom_dir = "overrides"

features = [
    "content.code.copy",
    "content.code.select",
    "navigation.footer",
    "navigation.indexes",
    "navigation.path",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.integrate",
]

[project.markdown_extensions.toc]
toc_depth = 2

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
